workflows:
  react-native-ios:
    name: Build iOS App
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "apps/mobile-app/ios/Thenga.xcworkspace"
        XCODE_SCHEME: "Thenga"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        APPLE_ID: Encrypted(...)
        APPLE_APP_SPECIFIC_PASSWORD: Encrypted(...)
        APP_STORE_CONNECT_API_KEY: Encrypted(...)
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd apps/mobile-app
          npm install
      - name: Install iOS dependencies
        script: |
          cd apps/mobile-app/ios
          pod install
      - name: Bundle React Native assets
        script: |
          cd apps/mobile-app
          npx react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle
      - name: Build iOS
        script: |
          cd apps/mobile-app/ios
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        apple_id: $APPLE_ID
        submit_to_testflight: true

  react-native-android:
    name: Build Android App
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.thenga.mobileapp"
        GOOGLE_PLAY_SERVICE_ACCOUNT: Encrypted(...)
        GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY: Encrypted(...)
      node: 18
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          cd apps/mobile-app
          npm install
      - name: Build Android
        script: |
          cd apps/mobile-app
          npx react-native run-android --variant=release
    artifacts:
      - build/android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
