workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.thenga.commerce
      vars:
        BUNDLE_ID: "com.thenga.commerce"
        XCODE_PROJECT: "apps/mobile-app/ios/Thenga.xcodeproj"
        XCODE_SCHEME: "Thenga"
        APP_STORE_APPLE_ID: 1097265059220834
        APP_STORE_APP_SECRET: "3f1cf7aad0f4b83dc44714d21b62fdcb"
        APPLE_ID: "m.olaniyan@icloud.com"
        TEAM_ID: "YJJA9A296N"
        SUPPORT_EMAIL: "support@thenga.mozdev.co.za"
        SUPPORT_URL: "https://thenga.mozdev.co.za/support"
        MARKETING_URL: "https://thenga.mozdev.co.za"
    scripts:
      - name: Install npm dependencies
        script: | 
          cd apps/mobile-app
          npm install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Install CocoaPods dependencies
        script: | 
          cd apps/mobile-app/ios && pod install
      - name: Increment build number
        script: | 
          cd apps/mobile-app/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/apps/mobile-app/ios/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - olaniyan4m@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        apple_id: m.olaniyan@icloud.com
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: false

  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.thenga.commerce"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/apps/mobile-app/android/local.properties"
      - name: Install npm dependencies
        script: | 
          cd apps/mobile-app
          npm install
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd apps/mobile-app/android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - apps/mobile-app/android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - olaniyan4m@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
