workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    # integrations:
    #   app_store_connect: codemagic
    environment:
      # ios_signing:
      #   distribution_type: development
      #   bundle_identifier: com.thenga.commerce
      vars:
        BUNDLE_ID: "com.thenga.commerce"
        XCODE_PROJECT: "apps/mobile-app/ios/Thenga.xcodeproj"
        XCODE_SCHEME: "Thenga"
        APP_STORE_APPLE_ID: 1097265059220834
        APP_STORE_APP_SECRET: "3f1cf7aad0f4b83dc44714d21b62fdcb"
        APPLE_ID: "m.olaniyan@icloud.com"
        TEAM_ID: "YJJA9A296N"
        SUPPORT_EMAIL: "support@thenga.mozdev.co.za"
        SUPPORT_URL: "https://thenga.mozdev.co.za/support"
        MARKETING_URL: "https://thenga.mozdev.co.za"
    scripts:
      - name: Install dependencies
        script: | 
          # Check Node.js and npm versions
          node --version
          npm --version
          
          # Install mobile app dependencies directly
          echo "Installing mobile app dependencies..."
          cd apps/mobile-app
          npm install --legacy-peer-deps --no-optional
          
          # Create node_modules symlink in root for CocoaPods
          cd ../..
          ln -sf apps/mobile-app/node_modules node_modules
      - name: Skip code signing setup
        script: |
          echo "Building without code signing for simulator"
      - name: Fix boost checksum and setup CocoaPods
        script: | 
          cd apps/mobile-app/ios
          
          # Debug: Show current directory and files
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          
          # Remove existing Pods to start fresh
          rm -rf Pods/ Podfile.lock
          
          # Install CocoaPods
          gem install cocoapods --no-document
          
          # Clear all CocoaPods caches
          pod cache clean --all
          
          # Try to fix the boost checksum issue by modifying Podfile
          echo "Modifying Podfile to fix boost checksum issue..."
          cat > Podfile << 'EOF'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '17.0'
prepare_react_native_project!

# Specify the Xcode project
project 'Thenga.xcodeproj'

target 'Thenga' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Disable Flipper for now
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix boost checksum issue
    installer.pods_project.targets.each do |target|
      if target.name == 'boost'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'BOOST_NO_CXX11_HDR_ARRAY=1'
        end
      end
    end
  end
end
EOF
          
          # Try installing with the modified Podfile
          pod install --repo-update --verbose || {
            echo "First attempt failed, trying with CDN..."
            pod install --repo-update --verbose --use-modular-headers
          }
          
          # Verify workspace was created
          echo "Checking for workspace file:"
          ls -la *.xcworkspace
      - name: Set build number
        script: | 
          cd apps/mobile-app/ios
          agvtool new-version -all $BUILD_NUMBER
      - name: Build for iOS Simulator
        script: | 
          cd apps/mobile-app/ios
          
          # Build using the workspace file created by CocoaPods
          xcodebuild -workspace Thenga.xcworkspace -scheme Thenga -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15' build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - apps/mobile-app/ios/build/**/*.app
      - apps/mobile-app/ios/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - olaniyan4m@gmail.com
        notify:
          success: true
          failure: false
      # app_store_connect:
      #   auth: integration
      #   apple_id: m.olaniyan@icloud.com
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Testers
      #   submit_to_app_store: false

  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.thenga.commerce"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/apps/mobile-app/android/local.properties"
      - name: Install npm dependencies
        script: | 
          cd apps/mobile-app
          npm install
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd apps/mobile-app/android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - apps/mobile-app/android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - olaniyan4m@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
