require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '17.0'
prepare_react_native_project!

# Enable modular headers for Swift pods
use_modular_headers!

project 'Thenga.xcodeproj'

target 'Thenga' do
  config = use_native_modules!
  flags = get_default_flags()

  # ✅ Force CocoaPods to use local Boost with correct checksum
  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec', :inhibit_warnings => true


  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix deployment target warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
