apiVersion: apps/v1
kind: Deployment
metadata:
  name: Thenga-api-gateway
  labels:
    app: Thenga-api-gateway
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Thenga-api-gateway
  template:
    metadata:
      labels:
        app: Thenga-api-gateway
        tier: backend
    spec:
      containers:
      - name: api-gateway
        image: Thenga/api-gateway:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: Thenga-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: Thenga-secrets
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: Thenga-secrets
              key: jwt-refresh-secret
        - name: REDIS_HOST
          value: "Thenga-redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: Thenga-api-gateway
  labels:
    app: Thenga-api-gateway
spec:
  selector:
    app: Thenga-api-gateway
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Thenga-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.Thenga.co.za
    secretName: Thenga-api-tls
  rules:
  - host: api.Thenga.co.za
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: Thenga-api-gateway
            port:
              number: 3001
