apiVersion: apps/v1
kind: Deployment
metadata:
  name: pezela-postgres
  labels:
    app: pezela-postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pezela-postgres
  template:
    metadata:
      labels:
        app: pezela-postgres
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "pezela"
        - name: POSTGRES_USER
          value: "pezela"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pezela-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - pezela
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - pezela
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pezela-postgres
  labels:
    app: pezela-postgres
spec:
  selector:
    app: pezela-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
